version: '3.4'
services:
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  splitwise:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/
    container_name: api_server
    environment:
      DB_PASSWORD: "postgres"
      DB_USER: "postgres"
      POSTGRES_DB: "test_db"
      DB_PORT: "5432"
      DB_HOST: "postgres"
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - /by/logs:/by/logs
      - ./postgres-data:/var/lib/postgresql/data